#!/usr/bin/env python3
"""Regenerate wiki/objective-map.md: the 64 official AI-103 objectives → wiki pages → sources.

Built from scripts/data/exam-objectives.json (wording verified verbatim against the study
guide, SRC-191) and two frontmatter fields on concept, entity and synthesis pages:

- `objectives`     — objectives the page substantively teaches from corpus evidence;
- `objective_gaps` — objectives the page discusses only to record that the corpus names them
                     (usually in the study guide) without teaching them.

Each objective gets a status: **taught** (at least one page teaches it and no gap is recorded),
**taught in part** (taught, and the gap register [[corpus-gaps]] records an untaught part),
**named only** (no page teaches it; the gap is recorded) or **no page**. Deterministic; never edit
by hand.

Usage (from the repo root):  python scripts/build_objective_map.py
"""
from __future__ import annotations

import datetime as _dt
import json
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "objective-map.md"
OBJECTIVES = ROOT / "scripts" / "data" / "exam-objectives.json"


def load_fm(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---", 3)
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return {}


def links(pages: list[tuple[str, dict]]) -> str:
    ordered = sorted(pages, key=lambda x: (x[1].get("type") != "concept", x[0]))
    return " · ".join(f"[[{s}|{fm.get('title') or s}]]" for s, fm in ordered)


def main() -> None:
    data = json.loads(OBJECTIVES.read_text(encoding="utf-8"))
    objectives = data["objectives"]
    taught: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    named: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    sources_for: dict[str, set[str]] = defaultdict(set)
    for p in sorted(WIKI.rglob("*.md")):
        fm = load_fm(p)
        if fm.get("type") not in {"concept", "entity", "synthesis"}:
            continue
        for o in fm.get("objectives") or []:
            taught[o].append((p.stem, fm))
            sources_for[o] |= set(fm.get("source_ids") or [])
        for o in fm.get("objective_gaps") or []:
            named[o].append((p.stem, fm))
    reg_path = WIKI / "synthesis" / "corpus-gaps.md"
    has_gaps = reg_path.exists()
    register = set((load_fm(reg_path).get("objective_gaps") or [])) if has_gaps else set()
    today = _dt.date.today().isoformat()
    n_full = sum(1 for o in objectives if taught.get(o["id"]) and o["id"] not in register)
    n_part = sum(1 for o in objectives if taught.get(o["id"]) and o["id"] in register)
    n_named = sum(1 for o in objectives if not taught.get(o["id"]) and (named.get(o["id"]) or o["id"] in register))
    n_none = len(objectives) - n_full - n_part - n_named
    out = [
        "---",
        "title: Exam objective map",
        "type: index",
        "status: active",
        "confidence: high",
        "created: 2026-09-24",
        f"updated: {today}",
        f"summary: The 64 official AI-103 objectives mapped to wiki pages — {n_full} taught, {n_part} taught in part, {n_named} named only, {n_none} with no page.",
        "area: exam",
        "source_ids: [SRC-191]",
        "tags: [navigation, exam, objectives]",
        "aliases: [objective map, skills measured map]",
        "---",
        "",
        "# Exam objective map",
        "",
        f"Generated by `scripts/build_objective_map.py` on {today}; do not edit by hand. Objective",
        "wording is quoted verbatim from the official study guide (SRC-191, *Skills measured as of",
        "April 16, 2026*) with its line number; IDs follow the app's numbering",
        "(`app/src/data/objectives.ts`). **Taught** lists pages whose frontmatter `objectives` claims",
        "corpus-backed teaching; **Named only** lists pages that record the objective as a corpus gap",
        "(`objective_gaps`). " + ("Gap detail is on [[corpus-gaps]]. " if has_gaps else "") + "Back to [[index]].",
        "",
        f"**{n_full} of {len(objectives)} objectives are taught · {n_part} taught in part (a named part is untaught; see the gap register) · {n_named} named only · {n_none} have no page.**",
        "",
    ]
    current_domain = current_skill = None
    for o in objectives:
        if o["domain"] != current_domain:
            current_domain = o["domain"]
            out += [f"## {o['domain']} ({o['weight']})", ""]
            current_skill = None
        if o["skill"] != current_skill:
            current_skill = o["skill"]
            out += [f"### {o['skill']}", ""]
        t, g = taught.get(o["id"], []), named.get(o["id"], [])
        gap = o["id"] in register
        status = ("taught in part" if gap else "taught") if t else ("named only" if (g or gap) else "no page")
        out.append(f"- **{o['id']}** `{status}` — “{o['objective']}” (SRC-191 L{o['line']})")
        if t:
            n_src = len(sources_for.get(o["id"], set()))
            out.append(f"  - Taught: {links(t)} · {n_src} sources cited across them")
        if g:
            out.append(f"  - Named only: {links(g)}")
        if not t and not g:
            out.append("  - *No wiki page yet.*")
    out += ["", "## Sources", "", "- SRC-191 — the official study guide (raw file in `corpus/`)."]
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"objective-map.md: {n_full} taught · {n_part} taught in part · {n_named} named only · {n_none} no page (of {len(objectives)})")


if __name__ == "__main__":
    main()
