#!/usr/bin/env python3
"""Regenerate wiki/objective-map.md: the 64 official AI-103 objectives → wiki pages → sources.

Built from scripts/data/exam-objectives.json (wording verified verbatim against the study
guide, SRC-191) and the `objectives` field in wiki page frontmatter. An objective with no
concept, entity or synthesis page is a coverage gap in the wiki; whether the *corpus* covers
it is recorded on [[corpus-gaps]]. Deterministic; never edit by hand.

Usage (from the repo root):  python scripts/build_objective_map.py
"""
from __future__ import annotations

import datetime as _dt
import json
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "objective-map.md"
OBJECTIVES = ROOT / "scripts" / "data" / "exam-objectives.json"


def load_fm(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---", 3)
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return {}


def main() -> None:
    data = json.loads(OBJECTIVES.read_text(encoding="utf-8"))
    objectives = data["objectives"]
    pages_for: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    sources_for: dict[str, set[str]] = defaultdict(set)
    for p in sorted(WIKI.rglob("*.md")):
        fm = load_fm(p)
        if fm.get("type") not in {"concept", "entity", "synthesis"}:
            continue
        for o in fm.get("objectives") or []:
            pages_for[o].append((p.stem, fm))
            sources_for[o] |= set(fm.get("source_ids") or [])
    has_gaps = (WIKI / "synthesis" / "corpus-gaps.md").exists()
    today = _dt.date.today().isoformat()
    covered = sum(1 for o in objectives if pages_for.get(o["id"]))
    out = [
        "---",
        "title: Exam objective map",
        "type: index",
        "status: active",
        "confidence: high",
        "created: 2026-09-24",
        f"updated: {today}",
        f"summary: The 64 official AI-103 objectives mapped to wiki pages and sources — {covered} of 64 have at least one concept, entity or synthesis page.",
        "area: exam",
        "source_ids: [SRC-191]",
        "tags: [navigation, exam, objectives]",
        "aliases: [objective map, skills measured map]",
        "---",
        "",
        "# Exam objective map",
        "",
        f"Generated by `scripts/build_objective_map.py` on {today}; do not edit by hand. Objective",
        "wording is quoted verbatim from the official study guide (SRC-191, *Skills measured as of",
        "April 16, 2026*) with its line number; IDs follow the app's numbering",
        "(`app/src/data/objectives.ts`). Pages appear here when their frontmatter lists the",
        "objective. " + ("Where the corpus itself is thin, see [[corpus-gaps]]. " if has_gaps else "")
        + "Back to [[index]].",
        "",
        f"**{covered} of {len(objectives)} objectives have a wiki page.**",
        "",
    ]
    current_domain = current_skill = None
    for o in objectives:
        if o["domain"] != current_domain:
            current_domain = o["domain"]
            out += [f"## {o['domain']} ({o['weight']})", ""]
            current_skill = None
        if o["skill"] != current_skill:
            current_skill = o["skill"]
            out += [f"### {o['skill']}", ""]
        ps = sorted(pages_for.get(o["id"], []), key=lambda x: ((x[1].get("type") != "concept"), x[0]))
        links = " · ".join(f"[[{s}|{fm.get('title') or s}]]" for s, fm in ps) or "*No wiki page yet.*"
        n_src = len(sources_for.get(o["id"], set()))
        out.append(f"- **{o['id']}** — “{o['objective']}” (SRC-191 L{o['line']})")
        out.append(f"  - Pages: {links}" + (f" · {n_src} sources cited across them" if n_src else ""))
    out += ["", "## Sources", "", "- SRC-191 — the official study guide (raw file in `corpus/`)."]
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"objective-map.md: {covered}/{len(objectives)} objectives have a wiki page")


if __name__ == "__main__":
    main()
