#!/usr/bin/env python3
"""Regenerate wiki/corpus-map.md: the course structure, source by source (schema.md §3, §10).

Lists every raw source under its learning path and Learn module (unit order), with the
matching episode transcript(s), a link to its source page, capture kind, teaching-content
size, ingest depth and the app lessons that already cite it (`sourceIds` in
app/src/data/curriculum/*.ts). Deterministic; never edit by hand.

Usage (from the repo root):  python scripts/build_corpus_map.py
"""
from __future__ import annotations

import datetime as _dt
import json
import re
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
OUT = WIKI / "corpus-map.md"
REGISTRY = ROOT / "scripts" / "data" / "corpus-registry.json"
CURRICULUM = ROOT / "app" / "src" / "data" / "curriculum"
UNIT_RE = re.compile(r"\bid:\s*'([a-z0-9-]+)',\s*\n?\s*title:\s*'")
IDS_RE = re.compile(r"sourceIds:\s*\[([0-9,\s]*)\]")
EP_TOKENS = re.compile(r"[a-z0-9]+")
STOP = {"a", "an", "the", "with", "in", "to", "and", "of", "for", "microsoft", "azure", "ai",
        "using", "by", "on", "use"}


def load_fm(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---", 3)
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return {}


def lessons_by_source() -> dict[int, list[str]]:
    out: dict[int, list[str]] = defaultdict(list)
    for f in sorted(CURRICULUM.glob("*.ts")):
        t = f.read_text(encoding="utf-8")
        for m in UNIT_RE.finditer(t):
            seg = t[m.start():m.start() + 6000]
            s = IDS_RE.search(seg)
            if s:
                for n in re.findall(r"\d+", s.group(1)):
                    out[int(n)].append(m.group(1))
    return out


def toks(s: str) -> set[str]:
    return set(EP_TOKENS.findall((s or "").lower())) - STOP


def main() -> None:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))["sources"]
    pages = {}
    for p in (WIKI / "sources").glob("src-*.md"):
        fm = load_fm(p)
        for sid in fm.get("source_ids") or []:
            pages[sid] = (p.stem, fm)
    lessons = lessons_by_source()

    modules: dict[str, list] = defaultdict(list)
    paths: dict[str, str] = {}
    aids, episodes = [], []
    for r in reg:
        if r["kind"] == "learn-unit":
            modules[r["module"] or "Unassigned"].append(r)
            if r.get("learning_path"):
                paths[r["module"]] = r["learning_path"]
        elif r["kind"] == "episode":
            episodes.append(r)
        else:
            aids.append(r)
    ep_by_module: dict[str, list] = defaultdict(list)
    for e in episodes:
        best = max(modules, key=lambda m: len(toks(m) & toks(e["module"])) / max(1, len(toks(m) | toks(e["module"]))))
        ep_by_module[best].append(e)

    def row(r: dict, unit: str) -> str:
        sid = r["sid"]
        stem, fm = pages.get(sid, (None, {}))
        title = r["display_title"].replace("|", "/")
        link = f"[[{stem}\\|{title}]]" if stem else f"{title} *(no source page yet)*"
        depth = fm.get("ingest_depth", "—") if stem else "—"
        les = ", ".join(sorted(set(lessons.get(r["id"], [])))) or "—"
        return f"| {sid} | {unit} | {link} | {r['content_words']} | {depth} | {les} |"

    header = ["| Source | Unit | Page | Content words | Ingest | App lessons |", "|---|---|---|---|---|---|"]
    today = _dt.date.today().isoformat()
    n_pages = sum(1 for r in reg if r["sid"] in pages)
    out = [
        "---",
        "title: Corpus map",
        "type: index",
        "status: active",
        "confidence: high",
        "created: 2026-09-24",
        f"updated: {today}",
        f"summary: The course structure source by source — {len(reg)} raw sources in {len(modules)} Learn modules plus {len(episodes)} episodes and {len(aids)} exam and course aids.",
        "area: corpus",
        "source_ids: []",
        "tags: [navigation, corpus]",
        "aliases: [course map, source map]",
        "---",
        "",
        "# Corpus map",
        "",
        f"Generated by `scripts/build_corpus_map.py` on {today} from `scripts/data/corpus-registry.json`;",
        "do not edit by hand. Each Learn module lists its units in order, then the AI-103 episode",
        "transcript that teaches the same module. *Content words* counts only the teaching text",
        "(Learn captures wrap it in site navigation). *App lessons* are the tutor lessons whose",
        "`sourceIds` already cite the source. Back to [[index]].",
        "",
        f"**{n_pages} of {len(reg)} sources have a source page.**",
        "",
        "## Exam, course and study aids",
        "",
    ] + header
    for r in sorted(aids, key=lambda r: r["id"]):
        out.append(row(r, r["kind"].replace("-", " ")))
    out.append("")

    order = sorted(modules, key=lambda m: (paths.get(m) is None, paths.get(m) or "", m))
    current = None
    for m in order:
        lp = paths.get(m) or "Modules reached outside a learning path"
        if lp != current:
            out += [f"## {lp}", ""]
            current = lp
        units = sorted(modules[m], key=lambda r: (r.get("unit_index") or 0, r["id"]))
        total = next((u["unit_total"] for u in units if u.get("unit_total")), None)
        out += [f"### {m}", "", f"{len(units)} captured units" + (f" of {total}" if total else "")
                + (f" · {len(ep_by_module[m])} episode(s)" if ep_by_module.get(m) else ""), ""] + header
        for r in units:
            out.append(row(r, str(r.get("unit_index") or "?")))
        for e in sorted(ep_by_module.get(m, []), key=lambda r: r["episode"] or 0):
            out.append(row(e, f"episode {e['episode']}"))
        out.append("")

    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"corpus-map.md: {len(reg)} sources, {len(modules)} modules, {n_pages} with source pages")


if __name__ == "__main__":
    main()
